services:
  minio:
    container_name: minio-telegram-bot
    volumes:
      - minio-data:/data
      - ./minio-init.sh:/usr/local/bin/minio-init.sh:ro
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z-cpuv1
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
      - MINIO_BROWSER_REDIRECT_URL=http://localhost:9001
      - MINIO_SERVER_URL=http://localhost:9000
    command: ["/usr/local/bin/minio-init.sh"]
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s

volumes:
  minio-data:
    driver: local
