services:
  telegram-bot-1:
    container_name: telegram-bot-1
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - file-management-telegram-bot:latest
    image: file-management-telegram-bot:latest
    env_file:
      - .env
    volumes:
      # todo isolate this
      - ./apps:/app/apps/:ro
      - ./apps/config:/app/apps/config/:ro
      - django-data-1:/app/data/
    restart: unless-stopped
    ports:
      - "8384:8000"
        #    depends_on:
        #      - redis
    networks:
        - local-network
#
#  redis:
#    container_name: redis
#    image: redis:latest
#    networks:
#        - local-network
#      

volumes:
  django-data-1:
    driver: local
networks:
  local-network: {} 
