services:
  minio:
      container_name: minio-telegram-bot
      volumes:
        - minio-data:/data
      image: minio/minio:latest
      environment:
        - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
        - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
      command: server /data --console-address ":9001" --address ":9000"
      ports:
        - "9000:9000"
        - "9001:9001"
volumes:
  minio-data:
    driver: local