services:
  telegram-bot:
    container_name: telegram-bot
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - file-management-telegram-bot:latest
    depends_on:
      - minio
    image: file-management-telegram-bot:latest
    
    networks:
      private-connection:
        ipv4_address: "172.19.1.1"
    env_file:
      - .env
    volumes:
      - django-data:/app/data/
    

  minio:
    container_name: minio-telegram-bot
    volumes:
      - minio-data:/data
    image: minio/minio:RELEASE.2025-04-08T15-41-24Z
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    networks:
      private-connection:
        ipv4_address: "172.19.1.2"
    command: server /data --console-address ":9001"

  nginx:
    container_name: nginx-telegram-bot
    build:
      context: .
      dockerfile: Dockerfile.nginx  # Reference the custom Nginx Dockerfile
    ports:
      - "8880:80"    # Map HTTP port to host
    volumes:
      - nginx-data:/var/log/nginx  # Persist Nginx logs
    depends_on:
      - minio
    networks:
      private-connection:
        ipv4_address: "172.19.1.3"
      internet-facing:
        ipv4_address: "172.20.1.1"

networks:
  private-connection:
    name: private-connection
    ipam:
      driver: default
      config:
        - subnet: "172.19.0.0/16"
  internet-facing:
    name: internet-facing
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"

volumes:
  minio-data:
    driver: local
  django-data:
    driver: local
  nginx-data:
    driver: local
