services:
  telegram-bot:
    container_name: telegram-bot
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - file-management-telegram-bot:latest
    depends_on:
      - telegram-bot-api
    image: file-management-telegram-bot:latest
    env_file:
      - .env
    volumes:
      # todo isolate this
      - ./apps:/app/apps/:ro
      - ./apps/config:/app/apps/config/:ro
      - django-data:/app/data/
    restart: unless-stopped

volumes:
  django-data:
    driver: local
