services:
  file-management-telegram-bot:
    container_name: telegram-bot
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - file-management-telegram-bot:latest
    image: file-management-telegram-bot:latest
    networks:
      - nat_connection
    env_file:
      - .env

  minio:
    container_name: minio_telegram_bot
    volumes:
      - minio_data:/data
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY_FILE={MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY_FILE={MINIO_SECRET_KEY}
    networks:
      - nat_connection

networks:
  nat_connection:
    driver: bridge

volumes:
  minio_data:
    driver: local
