# Generated by Django 5.2.4 on 2025-07-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_user_is_permiume_user_remaining_download_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="maximum_download_size_per_day",
            field=models.IntegerField(
                default=20,
                help_text="Maximum download size per day in bytes for the user.",
                verbose_name="maximum download size per day",
            ),
        ),
    ]
