# Generated by Django 5.2.4 on 2025-07-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_rename_is_permiume_user_is_premium"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="Optional. The user's first name.",
                max_length=30,
                null=True,
                verbose_name="first name",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="Optional. The user's last name.",
                max_length=30,
                null=True,
                verbose_name="last name",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(
                blank=True,
                help_text="identifier for the user in Telegram.",
                max_length=50,
                null=True,
                verbose_name="telegram ID",
            ),
        ),
    ]
